import type { Chore, Reward, PetState, AppSettings } from '../types';

export const DEFAULT_PIN_HASH = '1234'; // Simple default PIN for first setup

export const DEFAULT_SETTINGS: AppSettings = {
  id: 'global_settings',
  childName: 'My Champion',
  currentStars: 5,
  totalEarnedStars: 5,
  currentStreakDays: 1,
  lastActiveDate: new Date().toISOString().split('T')[0],
  pinHash: DEFAULT_PIN_HASH,
  requireApproval: false,
  soundEnabled: true,
  hapticsEnabled: true,
};

export const DEFAULT_PET: PetState = {
  type: 'capybara',
  name: 'Boba',
  happiness: 80,
  level: 1,
  totalFedCount: 0,
};

export const DEFAULT_CHORES: Omit<Chore, 'id'>[] = [
  // Morning Routine
  {
    title: 'Brush Teeth & Wash Face',
    icon: '🪥',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Make My Bed',
    icon: '🛏️',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Get Dressed for the Day',
    icon: '👗',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Eat a Healthy Breakfast',
    icon: '🥞',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },

  // Afternoon Routine
  {
    title: 'Unpack Backpack & Hang Jacket',
    icon: '🎒',
    routine: 'afternoon',
    starsReward: 1,
    repeat: 'weekdays',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Read a Book for 20 Minutes',
    icon: '📖',
    routine: 'afternoon',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Finish School Homework',
    icon: '✏️',
    routine: 'afternoon',
    starsReward: 2,
    repeat: 'weekdays',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Tidy Up Toys & Play Area',
    icon: '🧸',
    routine: 'afternoon',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },

  // Evening Routine
  {
    title: 'Put On Pajamas',
    icon: '🌙',
    routine: 'evening',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Nighttime Brush & Floss',
    icon: '🪥',
    routine: 'evening',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Pack Backpack for Tomorrow',
    icon: '📚',
    routine: 'evening',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Lights Out On Time',
    icon: '💤',
    routine: 'evening',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },

  // Bonus Quests
  {
    title: 'Water the House Plants',
    icon: '🌿',
    routine: 'bonus',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Help Set or Clear the Dinner Table',
    icon: '🍽️',
    routine: 'bonus',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Help Wash or Put Away Laundry',
    icon: '🧺',
    routine: 'bonus',
    starsReward: 3,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
];

export const DEFAULT_REWARDS: Omit<Reward, 'id'>[] = [
  {
    title: '30 Mins iPad Game Time',
    icon: '🎮',
    costInStars: 5,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Pick Dessert After Dinner',
    icon: '🍦',
    costInStars: 8,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Pick Family Movie Night',
    icon: '🎬',
    costInStars: 15,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Stay Up 30 Mins Past Bedtime',
    icon: '🌙',
    costInStars: 20,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Trip to the Ice Cream Parlor',
    icon: '🍧',
    costInStars: 25,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Special Toy or Book Treat',
    icon: '🎁',
    costInStars: 40,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
];
