import type { Chore, Reward, PetState, AppSettings, TimeframeGoals, Achievement } from '../types';

export const DEFAULT_PIN_HASH = '1234'; // Simple default PIN for first setup

export const DEFAULT_GOALS: TimeframeGoals = {
  dailyChoresTarget: 5,
  dailyStarsTarget: 10,
  weeklyChoresTarget: 30,
  weeklyStarsTarget: 60,
  monthlyChoresTarget: 120,
  monthlyStarsTarget: 250,
};

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  // Daily achievements
  {
    id: 'daily_first_step',
    title: 'First Step',
    description: 'Complete your first chore of the day',
    icon: '🌱',
    timeframe: 'daily',
    targetValue: 1,
    currentValue: 0,
    unlocked: false,
  },
  {
    id: 'daily_goal_crusher',
    title: 'Daily Goal Crusher',
    description: 'Reach your daily chore goal (5 chores)',
    icon: '🎯',
    timeframe: 'daily',
    targetValue: 5,
    currentValue: 0,
    unlocked: false,
  },
  {
    id: 'daily_morning_champion',
    title: 'Morning Master',
    description: 'Complete all morning routine chores',
    icon: '🌅',
    timeframe: 'daily',
    targetValue: 4,
    currentValue: 0,
    unlocked: false,
  },
  // Weekly achievements
  {
    id: 'weekly_goal_hero',
    title: 'Weekly Hero',
    description: 'Complete 30 chores in a single week',
    icon: '🏆',
    timeframe: 'weekly',
    targetValue: 30,
    currentValue: 0,
    unlocked: false,
  },
  {
    id: 'weekly_school_star',
    title: 'Weekday Wonder',
    description: 'Complete chores 5 weekdays in a row',
    icon: '📚',
    timeframe: 'weekly',
    targetValue: 5,
    currentValue: 0,
    unlocked: false,
  },
  {
    id: 'weekly_weekend_warrior',
    title: 'Weekend Warrior',
    description: 'Complete 6 or more weekend chores',
    icon: '🚀',
    timeframe: 'weekly',
    targetValue: 6,
    currentValue: 0,
    unlocked: false,
  },
  // Monthly achievements
  {
    id: 'monthly_century_club',
    title: 'Century Club',
    description: 'Complete 100+ chores in a single month',
    icon: '👑',
    timeframe: 'monthly',
    targetValue: 100,
    currentValue: 0,
    unlocked: false,
  },
  {
    id: 'monthly_super_saver',
    title: 'Super Star Collector',
    description: 'Earn 250+ stars in a single month',
    icon: '⭐️',
    timeframe: 'monthly',
    targetValue: 250,
    currentValue: 0,
    unlocked: false,
  },
  {
    id: 'monthly_consistency_legend',
    title: 'Consistency Legend',
    description: 'Active for at least 20 days in a month',
    icon: '🔥',
    timeframe: 'monthly',
    targetValue: 20,
    currentValue: 0,
    unlocked: false,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  id: 'global_settings',
  childName: 'My Champion',
  currentStars: 5,
  totalEarnedStars: 5,
  currentStreakDays: 1,
  lastActiveDate: new Date().toISOString().split('T')[0],
  pinHash: DEFAULT_PIN_HASH,
  requireApproval: false,
  soundEnabled: true,
  hapticsEnabled: true,
  goals: DEFAULT_GOALS,
};

export const DEFAULT_PET: PetState = {
  type: 'capybara',
  name: 'Boba',
  happiness: 80,
  level: 1,
  totalFedCount: 0,
};

export const DEFAULT_CHORES: Omit<Chore, 'id'>[] = [
  // Morning Routine
  {
    title: 'Brush Teeth & Wash Face',
    icon: '🪥',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Make My Bed',
    icon: '🛏️',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Get Dressed for the Day',
    icon: '👗',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Eat a Healthy Breakfast',
    icon: '🥞',
    routine: 'morning',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },

  // Afternoon Routine
  {
    title: 'Unpack Backpack & Hang Jacket',
    icon: '🎒',
    routine: 'afternoon',
    starsReward: 1,
    repeat: 'weekdays',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Read a Book for 20 Minutes',
    icon: '📖',
    routine: 'afternoon',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Finish School Homework',
    icon: '✏️',
    routine: 'afternoon',
    starsReward: 2,
    repeat: 'weekdays',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Weekend Deep Clean Play Area',
    icon: '🧹',
    routine: 'afternoon',
    starsReward: 3,
    repeat: 'weekends',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },
  {
    title: 'Tidy Up Toys & Books',
    icon: '🧸',
    routine: 'afternoon',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 4,
  },

  // Evening Routine
  {
    title: 'Put On Pajamas',
    icon: '🌙',
    routine: 'evening',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Nighttime Brush & Floss',
    icon: '🪥',
    routine: 'evening',
    starsReward: 1,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Pack Backpack for Tomorrow',
    icon: '📚',
    routine: 'evening',
    starsReward: 1,
    repeat: 'weekdays',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Lights Out On Time',
    icon: '💤',
    routine: 'evening',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },

  // Bonus Quests
  {
    title: 'Water the House Plants',
    icon: '🌿',
    routine: 'bonus',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 0,
  },
  {
    title: 'Help Set or Clear the Dinner Table',
    icon: '🍽️',
    routine: 'bonus',
    starsReward: 2,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 1,
  },
  {
    title: 'Weekend Bike/Car Wash or Yard Help',
    icon: '🚲',
    routine: 'bonus',
    starsReward: 4,
    repeat: 'weekends',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 2,
  },
  {
    title: 'Help Wash or Put Away Laundry',
    icon: '🧺',
    routine: 'bonus',
    starsReward: 3,
    repeat: 'daily',
    status: 'todo',
    createdAt: new Date().toISOString(),
    orderIndex: 3,
  },
];

export const DEFAULT_REWARDS: Omit<Reward, 'id'>[] = [
  {
    title: '30 Mins iPad Game Time',
    icon: '🎮',
    costInStars: 5,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Pick Dessert After Dinner',
    icon: '🍦',
    costInStars: 8,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Pick Family Movie Night',
    icon: '🎬',
    costInStars: 15,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Stay Up 30 Mins Past Bedtime',
    icon: '🌙',
    costInStars: 20,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Trip to the Ice Cream Parlor',
    icon: '🍧',
    costInStars: 25,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Special Toy or Book Treat',
    icon: '🎁',
    costInStars: 40,
    status: 'available',
    createdAt: new Date().toISOString(),
  },
];

